---
title: "Machine Learning Frameworks"
author: Laxmikant 
description: "Machine Learning Frameworks"
slug: Machine Learning Frameworks
date: 2018-12-05
lastmod: 2018-12-05
categories: ["blogdown"]
tags: ["Data Science, Machine Learning Frameworks"]
summary: Machine Learning Frameworks
subtitle: Machine Learning Frameworks
lua:
  image:
    url: "/img/cover.png"
    width: 800
    height: 600
  author: "Laxmikant"
  output:
  html_document:
    df_print: kable
    toc: true
---

<!--more-->


```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE
)
```

## Machine Learning Frameworks

One of the most important advances in practical machine learning involved the
creation of frameworks. Frameworks automate many aspects of developing
machine learning applications, and they allow developers to re-use code and take
advantage of best practices. This discussion introduces five of the most popular
frameworks: 

- Torch, 
- Theano, 
- Caffe, 
- Keras
- TensorFlow.

### Torch

Torch is the first machine learning framework to attract a significant following.
Originally released in 2002 by Ronan Collobert, it began as a toolset for numeric
computing. Torch’s computations involve multidimensional arrays called tensors,
which can be processed with regular vector/matrix operations. Over time, Torch
acquired routines for building, training, and evaluating neural networks.
Torch garnered a great deal of interest from academics and corporations like IBM
and Facebook. But its adoption has been limited by its reliance on Lua as its interface
language. The other frameworks Theano, Caffe, Keras, and TensorFlow — can be interfaced through Python, which has emerged as the language of choice in the machine learning domain.

### Theano

In 2010, a machine learning group at the University of Montreal released Theano,
a library for numeric computation. Like NumPy, Theano provides a wide range of
Python routines for operating on multidimensional arrays. Unlike NumPy, Theano
stores operations in a data structure called a graph, which it compiles into high performance
code. Theano also supports symbolic differentiation, which makes it possible to find derivatives of functions automatically. Because of its high performance and symbolic differentiation, many machine learning developers have adopted Theano as their numeric computation toolset of choice. Developers particularly appreciate Theano’s ability to execute graphs on graphics processing units (GPUs) as well as central processing units (CPUs).

### Caffe

As part of his PhD dissertation at UC Berkeley, Yangqing Jia created Caffe, a framework
for developing image recognition applications. As others joined in the development,
Caffe expanded to support other machine learning algorithms and many
different types of neural networks. Caffe is written in C++, and like Theano, it supports GPU acceleration. This emphasis on performance has endeared Caffe to many academic and corporate developers. Facebook has become particularly interested in Caffe, and in 2007 it released
a reworked version called Caffe2. This version improves Caffe’s performance and
makes executing applications on smartphones possible.

### Keras

While other offerings focus on performance and breadth of capabilities, Keras is
concerned with modularity and simplicity of development. François Chollet created
Keras as an interface to other machine learning frameworks, and many
developers access Theano through Keras to combine Keras’s simplicity with
Theano’s performance. Keras’s simplicity stems from its small API and intuitive set of functions. These functions focus on accomplishing standard tasks in machine learning, which
makes Keras ideal for newcomers to the field but of limited value for those who
want to customize their operations. François Chollet released Keras under the MIT License, and Google has incorporated his interface into TensorFlow. For this reason, many TensorFlow developers prefer to code their neural networks using Keras.

### TensorFlow

Google’s gift to the world of machine learning. The Google Brain team released TensorFlow 1.0 in 2015, and as of the time of this writing, the current version is 1.4. It’s provided under the Apache 2.0 open source license, which means you’re free to use it, modify it, and
distribute your modifications. TensorFlow’s primary interface is Python, but like Caffe, its core functionality is written in C++ for improved performance. Like Theano, TensorFlow stores operations in a graph that can be deployed to a GPU, a remote system, or a network of
remote systems. In addition, TensorFlow provides a utility called TensorBoard, which makes visualizing graphs and their operations possible. Like other frameworks, TensorFlow supports execution on CPUs and GPUs. In addition, TensorFlow applications can be executed on the Google Cloud Platform (GCP). The GCP provides world-class processing power at relatively low cost, and, GCP processing is TensorFlow’s most important advantage.