---
title: "Machine Learning Overview"
author: Laxmi K Soni 
description: "Machine learning is the science, in which we focus on teaching machines or computers to perform certain tasks without being given specific instructions"
slug: Machine Learning Overview
date: 2020-01-05
lastmod: 2020-01-05
categories: ["Machine Learning"]
tags: ["Machine Learning"]
Summary: Machine learning is the science, in which we focus on teaching machines or computers to perform certain tasks without being given specific instructions
subtitle: Machine learning
featured: "img/main/machine-learning-12.jpg"
output:
  html_document:
    highlight: tango
    theme: flatly
    toc: yes
    toc_float: yes

---

<!--more-->


```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE
)
```

# `WHAT IS MACHINE LEARNING?`

Machine learning is fundamentally is just the science, in which we focus on teaching machines or computers to perform certain tasks without being given specific instructions. We want our machines to learn how to do something themselves without explaining it to them.

In order to do this, we oftentimes look at how the human brain works and try to design virtual brains that work in a similar manner.

Machine learning and artificial intelligence are not the same. Artificial intelligence is a broad field and every system that can learn and solve problems might be considered an AI. Machine learning is one specific approach to this broad field.

## `SUPERVISED LEARNING`

In machine learning we have different approaches or types. The two main approaches are supervised learning and unsupervised learning . So let’s first talk about supervised learning.

Here, we give our model a set of inputs and also the corresponding outputs, which are the desired results. In this way, the model learns to match certain inputs to certain outputs and it adjusts its structure. It learns to make connections between what was put in and what the desired output is. It understands the correlation. When trained well enough, we can use the model to make predictions for inputs that we don’t know the results for.

Classic supervised learning algorithms are regressions, classifications and support vector machines.


## `UNSUPERVISED LEARNING`

With unsupervised learning on the other hand, we don’t give our model the desired results while training. Not because we don’t want to but because we don’t know them. This approach is more like a kind of pattern recognition. We give our model a set of input data and it then has to look for patterns in it. Once the model is trained, we can put in new data and our model will need to make decisions. Since the model doesn’t get any information about classes or results, it has to work with similarities and patterns in the data and categorize or cluster it by itself.

Classic unsupervised learning algorithms are clustering, anomaly detection and some applications of neural networks.

## `REINFORCEMENT LEARNING`
Then there is a third type of machine learning called reinforcement learning . Here we create some model with a random structure. Then we just observe what it does and reinforce or encourage it, when we like what it does. Otherwise, we can also give some negative feedback. The more our model does what we want it to do, the more we reinforce it and the more “rewards” it gets. This might happen in form of a number or a grade, which represents the so-called fitness of the model.

In this way, our model learns what is right and what is wrong. You can imagine it a little bit like natural selection and survival of the fittest. We can create 100 random models and kill the 50 models that perform worst. Then the remaining 50 reproduce and the same process repeats. These kinds of algorithms are called genetic algorithms.
Classic reinforcement learning algorithms are genetic or evolutional algorithms.


## `DEEP LEARNING`
Another term that is always confused with machine learning is deep learning . Deep learning however is just one area of machine learning, namely the one, which works with neural networks. Neural networks are a very comprehensive and complex topic. 


## `FIELDS OF APPLICATION`

Actually, it would be easier to list all the areas in which machine learning doesn’t get applied rather than the fields of application. Despite that, we will take a quick look at some of the major areas, in which machine learning gets applied.

· Research

· Autonomous Cars

· Spacecraft

· Economics and Finance

· Medical and Healthcare

· Physics, Biology, Chemistry

· Engineering

· Mathematics

· Robotics

· Education

· Forensics

· Police and Military

· Marketing

· Search Engines

· GPS and Pathfinding Systems
