---
title: "Applying Logistic Regression"
author: Laxmi K Soni 
description: "A case study on applying logistic regression to stock market"
slug: Applying Logistic Regression
date: 2020-02-12
lastmod: 2020-02-12
categories: ["Stock Market","Logistic Regression"]
tags: ["Stock Market","Logistic Regression"]
Summary: Application of Logistic Regression to Stock movement prediction
subtitle: Application of Logistic Regression to Stock movement prediction
featured: "img/main/logistic-stock-8.jpg"
output:
  html_document:
    highlight: tango
    theme: flatly
    toc: yes
    toc_float: yes

---

```{r setup, include=FALSE}
library(tidyverse)
library(magick)
library(reticulate)

conda_list()[[1]][1] %>% 
  use_condaenv(required = TRUE)
use_python("C://Users//slaxm//CONDA~1//envs//myenv1//python.exe")

import_from_path("investpy","c:\\users\\slaxm\\.conda\\envs\\myenv1\\lib\\site-packages")
```


***1: Installing libraries

```{python, eval = FALSE}

pip install mpl-finance

pip install investpy

pip install talib

pip install scikit-learn


```


##### MPL-FINANCE

MPL-Finance is a library that works together with Matplotlib and allows us to use special visualization for finance. 

#### investpy
MPL-Finance is a library that works together with Matplotlib and allows us to use special visualization for finance. 


## Logistic Regression in Trading


Trading usually involves decision making. If you are able to predict the movement of a stock before trade then this will help you eliminate the bad trades. Logistic regression helps in forming a rule based on the past data set.


## Logistic Regression

A Logistic Regression is an approach, usually used for performing classification tasks, that uses a separating hyperplane in multidimensional space to perform a given task. Technically speaking, in a p dimensional space, a hyperplane is a flat subspace with p-1 dimensions. For example, In two-dimensions, a hyperplane is a flat one-dimensional subspace or a line. In three dimensions, a hyperplane is a flat two-dimensional subspace that is, a plane. 

If the dimensionality is greater than 3, it can be hard to visualize a hyperplane, but the notion of a p-1 dimensional space still applies. 
You can include R code in the document as follows:



# Trading using Logistic Regression in Python

Let me begin by explaining the agenda here:

1) Create an unsupervised ML ( machine learning) algorithm to predict the regimes.

2) Plot these regimes to visualize them.

3) Train a Logistic Regression Classifier algorithm with the regime as one of the features.

4) Use this Logistic Regression Classifier algorithm to predict the current day’s trend at the Opening of the market.

5) Visualize the performance of this strategy on the test data.


## Importing libraries and data


```{python}

import investpy
from datetime import datetime
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn import metrics
import numpy as np
import pandas as pd
import seaborn as sn
import matplotlib.pyplot as plt

````

```{python}

```


#### Fetching the data

```{python}

df = investpy.commodities.get_commodity_historical_data(commodity='MCX Silver',from_date='01/01/2020',to_date='11/08/2020', country = "India")

print(df.tail())

```

#### Creating lag returns

```{python}

tslagret = pd.DataFrame(index=df.index)
tslagret["Today"] = df["Close"]

no_lags = 5

for i in range(0, no_lags):
    tslagret["Lag%s" % str(i + 1)] = df["Close"].shift(i + 1)

```

#### Creating returns dataframe
```{python}

df_ret = pd.DataFrame(index=tslagret.index)


df_ret["Today"] = tslagret["Today"].pct_change()*100.0

```


#### create the lagged percentage returns columns
```{python}
for i in range(0, no_lags):
    df_ret["Lag%s" % str(i + 1)] = tslagret["Lag%s" % str(i + 1)].pct_change() * 100.0

df_ret.drop(df_ret.index[:6], inplace=True)

```

####  "Direction" column (+1 or -1) indicating an up/down day

```{python}
df_ret["Direction"] = np.sign(df_ret["Today"])

data = df_ret

X = data[["Lag1", "Lag2", "Lag3", "Lag4","Lag5"]]

y = data["Direction"]

print(data.tail())

```


####  Create training and test sets

```{python}
start_test = datetime(2020, 8, 3)

X_train = X[X.index < start_test]
X_test = X[X.index >= start_test]
y_train = y[y.index < start_test]
y_test = y[y.index >= start_test]
```

####  Create model
```{python}
model = LogisticRegression()

```

####  train the model on the training set
```{python}
model.fit(X_train, y_train)
```

####  make an array of predictions on the test set
```{python}
y_pred = model.predict(X_test)
```

####  output the hit-rate and the confusion matrix for the model
```{python}
print('Accuracy: ',metrics.accuracy_score(y_test, y_pred))
```

```{python}
print(confusion_matrix(y_pred,y_test))
```

#### Predict returns

```{python}
X_test['y_actual'] = y_test
X_test['y_pred'] = y_pred
print(X_test)
```
