---
title: "Big Data Analytics"
author: Laxmi K Soni 
description: "Big-data helps to come to conclusion based on the data points arrived from the Big-data analysis, for instance Big-data can be in the form of Petabytes or hexabytes."
slug: Big Data Analytics
date: 2020-01-05
lastmod: 2020-01-05
categories: ["Big Data"]
tags: ["Big Data"]
Summary: Big-data helps to come to conclusion based on the data points arrived from the Big-data analysis, for instance Big-data can be in the form of Petabytes or hexabytes.
subtitle: Big Data
featured: "img/main/Big-Data-14.jpg"
output:
  blogdown::html_page:
    toc: false
  html_document:
    highlight: tango
    theme: flatly
    toc: false
---


## Big-data and Analytics:

Do we know how we can reach at a decision based on mobile data or computer data or Aadhar number? How to find that the new accounts that are opened in the Pradhan Mantri's Jan Dhan Yojana does not have enough money ?

How does company know that their brand is making consumers happy or not? OK, this works based on the Big-data Analytics. Lets us understand what this is,  When we call it Big Data Analytics then this directly links us i.e. consumer. Many companies are selling their products online. To find the righteousness of the sells Big-data helps.

Let us assume that someone is claiming that they have a certain number of hits of the consumer on their web-site, but those number of hits cannot be true unless the consumer have done those number of purchases because someone cannot be claimed as consumer unless he/she purchases something, now this indicates towards unstructured data. When data is structured and some conclusion is drawn from it then it will be known as Big Data Analysis.

Lets us understand it with the help of an example:-

There is a manufacturer of jewellery in Surat in India. He has started his website recently. Now he wants to increase the sales on the online platform only. He comes to Delhi and gets a very beautiful website. He has also made arrangements that his website shows up on the top of the google search results, now this kind or arrangement is known as search engine optimization. He is very excited from this. He was very excited that all over the world his website was visited by around 5000 people daily but within a month this excitement went down because out of those only 20 percent used to purchase. He was not able to understand the fact and was trying to increase the sales. Then one of his friends told him about Big data analytics firm in Bangalore. He was not able to understand that what that company will do. His friend told him that Big Data analysis will help him know the trends of the web site visited by the consumers. This will help him get the future strategy of the online jewelry business.

#### The Meaning of Big Data

Big-data helps to come to conclusion based on the data points arrived from the Big-data analysis, for instance Big-data can be in the form of Petabytes or hexabytes. This may contain the data or information about lakhs, crores or millions of people. This data may come from sources such as customers connect center, social media, mobile data etc. These kinds of numbers are known as structured data but these are not complete. To get to the roots of these is difficult.

Big-data & Analytics helps companies to arrive at a decision. This will help not only to get new information about the business but this helps in getting the big insights or trends which cannot be identified based on just numbers.

#### How it started

In September 1956 IBM has presented Random access memory accounting machine. This was the first disk storage product of the world. This has two kinds of machines. One was 305 with a capacity of 5 Megabyte and weight of 1 ton. Second was 650. Actually the use of these was done by telecommunications company to find whether the customers are happy or not. It can be identified with the help of an analysis.

In a report by Nasscom in partnership with Blue ocean market intelligence the market of big data is 1 Arab dollar i.e. around 62 Arab rupees.this will be more than double in 2017.

Big data helps to get different kinds of ideas. With the help of this we can bring the change in management. Regardless of the organization Big-data analysis helps to get insights. With the help of these insights company can form the future strategy.

From the point of view of the consumer it is important because it can increase the number of consumers.

#### Use

Big Data helps in decision making. Along with that it helps in getting the direction in which to put the efforts. In financial sector manufacturer of consumer products and telecommunications companies can identify "what the customer wants". Companies working in the banks and financial sector can find which kinds of loan are being taken more, how the loan is getting repaid. How much debt is getting lost and what are the reasons of that.

In the era of supply chain and new brands the interest of the consumer is getting identified with the help of Big-data. Crores of people give their opinion on social media on something and when it is about some brand then with the help of Big-data it is considered to find further insights. Similarly Big Data helps in getting an opinion based on the text, audio and video. What is making consumers happy can be identified with the help of big data analytics.

People use Big-data driven analytics to drive value in diverse fields such as

- Driving revenues in e-commerce
- Driving recommendations to consumers in various web applications such as social media, online retail, ads, etc.
- Healthcare applications including diagnosis of diseases
- Social sciences – predicting election outcomes and econometric models

In India the market for Big-data analytics is increasing at the rate of 45% and there are opportunities in every sector.
